"""
Fault-tolerant State Manager and Checkpoint Engine.
Ensures that generated content is never lost on network or API failures,
and allows seamless resumption to save LLM tokens and API quota.
"""

import json
import os
import tempfile
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional
from src.logger import logger

class StateStatus:
    IDLE = "IDLE"
    GENERATED = "GENERATED"       # Content generated by LLM, pending Buffer draft
    DRAFTING = "DRAFTING"         # Attempting Buffer API call
    FAILED = "FAILED"             # Failed at Buffer draft creation, ready to resume
    COMPLETED = "COMPLETED"       # Successfully drafted to Buffer


class StateManager:
    def __init__(self, state_file_path: str = "data/state.json", history_file_path: str = "data/history.jsonl"):
        self.state_file = Path(state_file_path)
        self.history_file = Path(history_file_path)
        
        # Ensure data directory exists
        self.state_file.parent.mkdir(parents=True, exist_ok=True)
        self.history_file.parent.mkdir(parents=True, exist_ok=True)
        
        self._init_state()

    def _init_state(self) -> None:
        """Initializes empty state file if it doesn't exist."""
        if not self.state_file.exists():
            default_state = {
                "cycle_id": None,
                "status": StateStatus.IDLE,
                "pending_post": None,
                "retry_count": 0,
                "last_error": None,
                "updated_at": datetime.now(timezone.utc).isoformat()
            }
            self._write_state_atomic(default_state)

    def _read_state(self) -> Dict[str, Any]:
        """Reads current state from disk."""
        try:
            if self.state_file.exists():
                with open(self.state_file, "r", encoding="utf-8") as f:
                    return json.load(f)
        except Exception as e:
            logger.warning(f"Could not read state file: {e}. Reinitializing.")
        return {
            "cycle_id": None,
            "status": StateStatus.IDLE,
            "pending_post": None,
            "retry_count": 0,
            "last_error": None,
            "updated_at": datetime.now(timezone.utc).isoformat()
        }

    def _write_state_atomic(self, state: Dict[str, Any]) -> None:
        """Writes state atomically using a temp file to prevent corruption."""
        state["updated_at"] = datetime.now(timezone.utc).isoformat()
        dir_path = self.state_file.parent
        with tempfile.NamedTemporaryFile("w", dir=dir_path, delete=False, encoding="utf-8") as tf:
            json.dump(state, tf, indent=2, ensure_ascii=False)
            temp_name = tf.name
        os.replace(temp_name, self.state_file)

    def has_pending_generation(self) -> bool:
        """Returns True if there is an unposted generated draft waiting in state."""
        state = self._read_state()
        return bool(state.get("pending_post") and state.get("status") in (StateStatus.GENERATED, StateStatus.FAILED))

    def get_pending_generation(self) -> Optional[Dict[str, Any]]:
        """Retrieves the pending post from state checkpoint."""
        state = self._read_state()
        if self.has_pending_generation():
            return state.get("pending_post")
        return None

    def save_generation(
        self,
        post_content: str,
        metadata: Dict[str, Any],
        image_data: Optional[Dict[str, Any]] = None,
        cycle_id: Optional[str] = None,
    ) -> str:
        """
        Saves freshly generated post and optional image data to checkpoint immediately.
        Saves API tokens & image quota if any subsequent step (Buffer API) fails.
        """
        active_cycle_id = cycle_id or str(uuid.uuid4())[:8]
        pending_post = {
            "cycle_id": active_cycle_id,
            "content": post_content,
            "metadata": metadata,
            "image_data": image_data,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "character_count": len(post_content),
            "estimated_reading_time_mins": max(1, round(len(post_content.split()) / 200, 1))
        }
        
        state = {
            "cycle_id": active_cycle_id,
            "status": StateStatus.GENERATED,
            "pending_post": pending_post,
            "retry_count": 0,
            "last_error": None,
            "updated_at": datetime.now(timezone.utc).isoformat()
        }
        self._write_state_atomic(state)
        logger.info(f"[green]✓ Content & image state saved to checkpoint (Cycle ID: {active_cycle_id})[/green]")
        return active_cycle_id

    def record_failure(self, error_message: str, stage: str = "buffer_draft") -> None:
        """Records error in state without erasing generated content so user can resume."""
        state = self._read_state()
        state["status"] = StateStatus.FAILED
        state["last_error"] = f"[{stage}] {error_message}"
        state["retry_count"] = state.get("retry_count", 0) + 1
        self._write_state_atomic(state)
        logger.warning(f"[yellow]Recorded failure in state: {error_message} (Retry count: {state['retry_count']})[/yellow]")

    def mark_completed(self, buffer_response: Dict[str, Any], profile_id: Optional[str] = None) -> None:
        """
        Marks generation cycle as complete, archives post to history.jsonl,
        and resets state to IDLE.
        """
        state = self._read_state()
        pending_post = state.get("pending_post") or {}
        
        update_id = buffer_response.get("id")
        if not update_id and isinstance(buffer_response.get("updates"), list) and buffer_response["updates"]:
            update_id = buffer_response["updates"][0].get("id")

        history_entry = {
            "cycle_id": state.get("cycle_id"),
            "completed_at": datetime.now(timezone.utc).isoformat(),
            "profile_id": profile_id,
            "buffer_update_id": update_id,
            "buffer_status": buffer_response.get("status") or "draft",
            "post_content": pending_post.get("content"),
            "metadata": pending_post.get("metadata", {}),
            "image_data": pending_post.get("image_data"),
            "character_count": pending_post.get("character_count", 0),
            "buffer_raw_response": buffer_response
        }


        # Append to history.jsonl
        with open(self.history_file, "a", encoding="utf-8") as f:
            f.write(json.dumps(history_entry, ensure_ascii=False) + "\n")

        # Reset active state to IDLE
        idle_state = {
            "cycle_id": None,
            "status": StateStatus.IDLE,
            "pending_post": None,
            "retry_count": 0,
            "last_error": None,
            "last_completed_at": datetime.now(timezone.utc).isoformat()
        }
        self._write_state_atomic(idle_state)
        logger.info(f"[green]✓ Successfully archived post to history log and cleared active state.[/green]")

    def clear_state(self) -> None:
        """Clears any stuck checkpoint and resets state."""
        idle_state = {
            "cycle_id": None,
            "status": StateStatus.IDLE,
            "pending_post": None,
            "retry_count": 0,
            "last_error": None,
            "updated_at": datetime.now(timezone.utc).isoformat()
        }
        self._write_state_atomic(idle_state)
        logger.info("[cyan]State checkpoint cleared.[/cyan]")

    def get_state(self) -> Dict[str, Any]:
        """Returns the current state dictionary."""
        return self._read_state()

    def get_recent_history(self, limit: int = 5) -> List[Dict[str, Any]]:
        """Returns the most recent published entries from history.jsonl."""
        if not self.history_file.exists():
            return []
        entries = []
        try:
            with open(self.history_file, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if line:
                        entries.append(json.loads(line))
        except Exception as e:
            logger.error(f"Error reading history file: {e}")
        return entries[-limit:][::-1]
